@startuml
entity productos {
  producto_id PK
  nombre_producto
  descripcion
  precio_unitario
  tipo_producto
}

entity tinas {
  tina_id PK
  nombre_tina
  tara
}

entity ventas {
  venta_id PK
  fecha_venta
  cliente_id FK
  total
}

entity detalles_venta {
  detalle_id PK
  venta_id FK
  producto_id FK
  tina_id FK
  cantidad
  precio_unitario
  subtotal
}

productos ||--o{ detalles_venta : contains
tinas ||--o{ detalles_venta : used_in
ventas ||--o{ detalles_venta : includes
@enduml
