@startuml
left to right direction
node "Navegador Web" {
    [Aplicación Web]
}

node "Internet" {
    interface "HTTP/HTTPS" as http
}

node "Servidor VPS (Ubuntu)" {

    node "Servidor Web (Nginx)" {
        interface "HTTP/HTTPS" as http_server
    }
        [Gateway Microservicio]
        [Eureka Microservicio]
        [Config Server Microservicio]
        [Ventas y Compras Microservicio]
        [Finanzas Microservicio]
        [Inventario Microservicio]
        [Entidades Microservicio]
        [Autenticación Microservicio]

    database "Base de Datos (PostgreSQL) AUTH" {
        [Autenticación Microservicio]
    }
    database "Base de Datos (PostgreSQL) ENTIDADES" {
            [Entidades Microservicio]
    }

    database "Base de Datos (PostgreSQL) INVENTARIO"{
     [Inventario Microservicio]
    }
    database "Base de Datos (PostgreSQL) FINANAZAS" {
         [Finanzas Microservicio]
    }
    database "Base de Datos (PostgreSQL) VENTAS Y COMPRAS"{
             [Ventas y Compras Microservicio]
    }
}

[Aplicación Web] --> http : Peticiones REST
http --> http_server : Proxy inverso
http_server --> [Gateway Microservicio] : Delegación de peticiones
[Gateway Microservicio] --> [Eureka Microservicio] : Registro de microservicios
[Gateway Microservicio] --> [Config Server Microservicio] : Obtención de configuraciones
[Gateway Microservicio] --> [Ventas y Compras Microservicio] : Peticiones de ventas y compras
[Gateway Microservicio] --> [Finanzas Microservicio] : Peticiones de finanzas
[Gateway Microservicio] --> [Inventario Microservicio] : Peticiones de inventario
[Gateway Microservicio] --> [Entidades Microservicio] : Peticiones de entidades
[Gateway Microservicio] --> [Autenticación Microservicio] : Peticiones de autenticación
[Autenticación Microservicio] --> [Base de Datos (PostgreSQL) AUTH] : JDBC
[Ventas y Compras Microservicio] --> [Base de Datos (PostgreSQL) VENTAS Y COMPRAS] : JDBC
[Finanzas Microservicio] --> [Base de Datos (PostgreSQL) FINANAZAS] : JDBC
[Inventario Microservicio] --> [Base de Datos (PostgreSQL) INVENTARIO] : JDBC
[Entidades Microservicio] --> [Base de Datos (PostgreSQL) ENTIDADES] : JDBC
@enduml
