server:
  port: 9095
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-finanzas

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/finanzas
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost               # Dirección del servidor RabbitMQ
    port: 5672                    # Puerto predeterminado de RabbitMQ
    username: guest                # Cambia esto si configuraste otro usuario
    password: guest                # Cambia esto si configuraste otra contraseña
    virtual-host: /                # El virtual host por defecto, puedes modificarlo si tienes uno personalizado
    listener:
      simple:
        concurrency: 5             # Número de consumidores concurrentes
        max-concurrency: 10        # Máximo número de consumidores

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
