@startuml

package "org-camal" {
    class ComprobanteVenta{
        -idEmpresa
        -idComprovanteV
        -idComprobanteVTipo
        -numero
        -serie
        -idCliente
        -fechaEmision
        -idEstado
        -usuCodigo // Usuario de creación
        -observaciones
        -idMonedas
    }
    class ComprobantesTipos {
        -idComprobanteTipo
        -codigo
        -descripcion
    }
    class ComprobantesEstados {
        -idComprobanteEstado
        -codigo
        -descripcion
    }
    class ComprobantesVentasCuotas {
        -idComprobanteCuota
        -idComprovanteV
        -numerocuota
        -fechavencimiento
        -montocuota
        -importe
        -idMonedas
    }
    interface ComprobanteVentaMetodos {
        + RegistrarVenta()
        + AnularVenta()
        + ObtenerComprobante()
    }
    ComprobanteVenta "n*" *-- "1" ComprobantesTipos : compocision
    ComprobanteVenta "n*" *-- "1" ComprobantesEstados : compocision
    ComprobanteVenta "1" *-- "n* - 0" ComprobantesVentasCuotas : compocision
    ComprobanteVenta --> ComprobanteVentaMetodos : implementa
    }

@enduml
