@startuml

package "org-camal-ventas" {
    class Comprobante{
        -idEmpresa
        -idComprobanteV
        -idComprobanteVTipo
        -numero
        -serie
        -idCliente
        -fechaEmision
        -idComprobanteTipo
        -idEstado
        -usuCodigo(usuario de creacion)
        -observaciones
        -idMonedas
    }
    class Ventas{
        - comprobante
        - comprobanteEstado
        - comprobanteTipo
        - cuotas
    }
    class Cuotas{
        - idCuota
        - idVenta
        - monto
        - fechaVencimiento
        - estado
    }
    interface IVentasService {
        - guardarVenta(ventaRequest)
        - anularVenta(id)
        - getComprobantesTiposVentas(IdEmpresa)
        - registrarPagoCuota(idCuota)
        - compensarVenta(venta)
    }
    class ComprobantesEstados {
        -idComprobanteEstado
        -codigo
        -descripcion
    }
    class ComprobantesTipos {
        -idComprobanteTipo
        -codigo
        -descripcion
    }

    Ventas "1" *-- "1" Comprobante : composicion
    Ventas "1" *-- "1" ComprobantesEstados : composicion
    Ventas "1" *-- "1" ComprobantesTipos : composicion
    Ventas "1" *-- "n" Cuotas : composicion
    Ventas --> IVentasService : implementa
    Comprobante "1*" *-- "1" ComprobantesEstados : composicion
    Comprobante "1*" *-- "1" ComprobantesTipos : composicion
}

@enduml
