@startuml

package "org-camal-compras" {
    class Comprobante{
        -idEmpresa
        -idComprovanteC
        -idComprobanteCTipo
        -numero
        -serie
        -idCliente
        -fechaEmision
        -idComprobanteTipo
        -idEstado
        -usuCodigo(usuario de creacion)
        -observaciones
        -idMonedas
    }
    class Compras{
        - comprobante
        - comprobanteEstado
        - comprobanteTipo
    }
    interface IComprasService {
        - guardarCompra(compraRequest)
        - anularCompra(id)
        - getComprobantesTiposCompras(IdEmpresa)
        - compensarCompra(compra)
    }
    class ComprobantesEstados {
        -idComprobanteEstado
        -codigo
        -descripcion
    }
    class ComprobantesTipos {
            -idComprobanteTipo
            -codigo
            -descripcion
        }

    Compras "1" *-- "1" Comprobante : composicion
    Compras "1" *-- "1" ComprobantesEstados : composicion
    Compras "1" *-- "1" ComprobantesTipos : composicion
    Compras --> IComprasService : implementa
    Comprobante "1" *-- "1" ComprobantesEstados : composicion
    Comprobante "1" *-- "1" ComprobantesTipos : composicion
}

@enduml