@startuml
actor "usuario" as cli
actor "administrador" as adm
package "con.compras" {
note "Se podra actualizar la informacion de los proveedores, como eliminarlos." as N2

    usecase "Registrar nueva Entidad" as en
    usecase "Consultar entidades" as recom
    usecase "Gestionas entidades" as ges
    usecase "gestionar trabajadores" as trabajadores
    usecase "Registrar asistentes" as asistentes
    ges ..N2
}
cli --> en :[101] registrar
cli --> recom :[102] consultar
adm --> ges :[103] gestionar
cli --> trabajadores :[104] gestionar
cli --> asistentes :[105] registrar


@enduml
