@startuml
!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&foreign></color> x

entity "Usuario" {
    primary_key(idUsuario) : INT
    nombre : VARCHAR
    password : VARCHAR
    foreign_key(rol) : INT
    activo : BOOLEAN
}

entity "Rol" {
    primary_key(idRol) : INT
    nombre : VARCHAR
}

entity "Permisos" {
    primary_key(idPermiso) : INT
    nombre : VARCHAR
}

entity "Menus" {
    primary_key(idMenu) : INT
    nombre : VARCHAR
}


Usuario ||--|{ Rol : "tiene"

Rol ||--|{ Permisos : "tiene"

Usuario ||--|{ Menus : "tiene"
@enduml