
server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthFilter
        - id: inventario
          uri: http://localhost:9091
          predicates:
            - Path=/api/inventario/**
          filters:
            - name: AuthFilter

        - id: ventas
          uri: http://localhost:9092
          predicates:
            - Path=/api/ventas/**
          filters:
            - name: AuthFilter
        - id: free-pass
          uri: http://localhost:9092
          predicates:
            - Path=/api/free-pass/**
          filters:
            - name: FreePassFilter

        - id: empresas
          uri: http://localhost:9093
          predicates:
            - Path=/empresas/**
          filters:
            - name: AuthFilter
        - id: finanzas
          uri: http://localhost:9095
          predicates:
            - Path=/api/finanzas/**
          filters:
            - name: AuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
jwt-key:
  password: 77bffaa03dd4271127062c7d10c55ca1b4bb8735ebb4aecaf4a8f877f87bdb29
  username: AUTHUSERJWT-BACKEND